### ISSUE TITLE
Simplify embed code, slightly?

### ISSUE THREAD

**Issue by tiesont** [fightforthefuture/idl-members#17]
Any particular reason the embed code has this;

```
idl.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'members.internetdefenseleague.org/include/?url=' + (_idl.url || '') + '&campaign=' + (_idl.campaign || '') + '&variant=' + (_idl.variant || 'banner');
```

when this works the same:

```
idl.src = '//members.internetdefenseleague.org/include/?url=' + (_idl.url || '') + '&campaign=' + (_idl.campaign || '') + '&variant=' + (_idl.variant || 'banner');
```

As Paul Irish explains here, http://www.paulirish.com/2010/the-protocol-relative-url/, it's only really an issue for IE6. I'll admit, it's not a huge change, but why evaluate a conditional if you don't have to?

**Comment by ChrisAntaki** [comment]
The embed is now leaner & meaner 08f7af06fcfc085635adfa314ba5dfd533f9326c
